files_path: "{{ role_path }}/files"

config_dir: "{{ ansible_facts.env.XDG_CONFIG_HOME | default('~/.config') }}"
cache_dir: "{{ ansible_facts.env.XDG_CACHE_HOME | default('~/.cache') }}"
data_dir: "{{ ansible_facts.env.XDG_DATA_HOME | default('~/.local/share') }}"
local_bin_dir: "{{ ansible_facts.env.HOME }}/.local/bin"

dot_cache_dir: "{{ cache_dir }}/eirrw/dotfiles"
