# xdg
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export PATH="${PATH}:${HOME}/.local/bin"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZCOMPDUMP="${XDG_CACHE_HOME}/zsh/zcompdump"

export HISTFILE="${XDG_CACHE_HOME}/zsh/zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

export _ZL_DATA="${XDG_CACHE_HOME}/zsh/zlua"

# style
export QT_STYLE_OVERRIDE=Adwaita-dark

# man
export MANPAGER='nvim +Man!'

# ls
# LS_COLORS provided by plugin

# golang
export GOPATH="${XDG_DATA_HOME}/go"
export PATH="${PATH}:${GOPATH}"
export PATH="${PATH}:/usr/local/go/bin/"

# node
export NVM_DIR="${XDG_DATA_HOME}/nvm"

# rust
export CARGO_HOME="${XDG_CACHE_HOME}/cargo"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export PATH="${PATH}:${CARGO_HOME}/bin"

# ssh
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

export MOZ_DISABLE_RDD_SANDBOX=1
export LIBVA_DRIVER_NAME=nvidia
export NVD_BACKEND=direct
