- name: install
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    packages:
      - fish

- name: create fish configuration directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ fish_conf_dir }}"
    - "{{ fish_conf_dir }}/completions"
    - "{{ fish_conf_dir }}/conf.d"
    - "{{ fish_conf_dir }}/functions"

- name: gather fish configuration files
  ansible.builtin.set_fact:
    files: "{{ files|default([]) + [ (item | dirname | split('/') | last) + '/' + (item | basename) ] }}"
  loop: >-
      {{ query('ansible.builtin.fileglob', files_path + '/fish/completions/*.fish')
      + query('ansible.builtin.fileglob', files_path + '/fish/conf.d/*.fish')
      + query('ansible.builtin.fileglob', files_path + '/fish/functions/*.fish') }}

- name: setup fish configuration files
  import_tasks: "{{ playbook_dir }}/shared/copy.yml"
  vars:
    src: "{{ files_path }}/fish/{{ item }}"
    dest: "{{ fish_conf_dir }}/{{ item }}"
    loop: "{{ files }}"

- name: get ls_colors config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/lscolors.csh
    dest: "{{ fish_conf_dir }}/conf.d/ls_colors.fish"
    mode: '0644'

- name: download fisher
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/refs/tags/4.4.5/functions/fisher.fish
    dest: "{{ dot_cache_dir }}/fisher.fish"
  register: fisher

- name: install fisher
  ansible.builtin.command:
    argv:
      - fish
      - --command
      - source {{ fisher.dest }} && fisher install jorgebucaran/fisher
    creates: "{{ fish_conf_dir }}/functions/fisher.fish"

- name: install fish plugins
  ansible.builtin.command:
    argv:
      - fish
      - --command
      - "fisher install {{ plugins | join(' ') }}"
  vars:
    plugins:
      - PatrickF1/fzf.fish
      - jethrokuan/z

- name: fish as primary shell
  ansible.builtin.blockinfile:
    path: "$HOME/.bash_profile"
    block: |
      if [ -n "${SHLVL}" ] && [ "${SHLVL}" -eq 1 ] && [ -z "${TOOLBOX_PATH}" ]; then
        exec fish
      fi
    insertafter: EOF
