- name: install
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    packages:
      - fish

- name: create base fish conf dir
  ansible.builtin.file:
    state: directory
    path: "{{ fish_conf_dir }}"

- name: create fish configuration directories
  ansible.builtin.file:
    state: directory
    path: "{{ fish_conf_dir }}/{{ item.path }}"
  loop: "{{ fish_conf_items }}"
  when: item.state == 'directory'
  loop_control:
    label: "{{ item.path }}"

- name: setup fish configuration files
  import_tasks: "{{ playbook_dir }}/shared/copy.yml"
  vars:
    src: "{{ item.src }}"
    dest: "{{ fish_conf_dir }}/{{ item.path }}"
    items: "{{ fish_conf_items | selectattr('state', 'eq', 'file') }}"

- name: get ls_colors config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/lscolors.csh
    dest: "{{ fish_conf_dir }}/conf.d/ls_colors.fish"
    mode: "0644"

- name: download fisher
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/refs/tags/4.4.5/functions/fisher.fish
    dest: "{{ dot_cache_dir }}/fisher.fish"
  register: fisher

- name: install fisher
  ansible.builtin.command:
    argv:
      - fish
      - --command
      - source {{ fisher.dest }} && fisher install jorgebucaran/fisher
    creates: "{{ fish_conf_dir }}/functions/fisher.fish"

- name: install fish plugins
  ansible.builtin.command:
    argv:
      - fish
      - --command
      - "fisher install {{ plugins | join(' ') }}"
  vars:
    plugins:
      - PatrickF1/fzf.fish
      - jethrokuan/z

- name: fish as primary shell
  ansible.builtin.blockinfile:
    path: "$HOME/.bash_profile"
    block: |
      if [[ $- == *i* ]] && [ -n "${SHLVL}" ] && [ "${SHLVL}" -eq 1 ] && [ -z "${TOOLBOX_PATH}" ]; then
        exec fish
      fi
    insertafter: EOF
