- name: download fnm archive
  ansible.builtin.get_url:
    url: https://github.com/Schniz/fnm/releases/latest/download/fnm-{{ fnm_arch | trim }}.zip
    dest: "{{ dot_cache_dir }}/fnm.zip"
    mode: '0644'
  when: (fnm_arch)
  register: result

- name: extract fnm
  ansible.builtin.unarchive:
    src: "{{ result.dest }}"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: '0755'
  when: (fnm_arch) and result.changed
