- import_tasks: fish.yml
  tags: [fish]

- name: create required directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ ansible_env.HOME }}/.local/bin"

- name: install and configure nvim
  block:
    - name: install
      import_tasks: "{{ playbook_dir }}/shared/install.yml"
      vars:
        packages:
          - neovim

    - name: check neovim config directory
      ansible.builtin.stat:
        path: "{{ nvim_conf_dir }}"
      register: nv

    - name: check lazyvim status
      ansible.builtin.stat:
        path: "{{ nvim_conf_dir }}/lazyvim.json"
      register: lv

    - name: backup old neovim config directory
      ansible.builtin.command:
        cmd: "mv {{ nvim_conf_dir }} {{ nvim_conf_dir }}.bak/"
        creates: "{{ nvim_conf_dir }}.bak"
        removes: "{{ nvim_conf_dir }}"
      when: "(nv.stat.islnk is defined and nv.stat.islnk == False) or (lv.stat.exists == False)"

    - name: remove old state files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ ansible_env.HOME }}/.local/share/nvim"
        - "{{ ansible_env.HOME }}/.local/state/nvim"
        - "{{ cache_dir }}/nvim"

    - name: setup neovim config files
      import_tasks: "{{ playbook_dir }}/shared/copy.yml"
      vars:
        src: "{{ files_path }}/nvim/"
        dest: "{{ nvim_conf_dir }}"

    - name: setup plugins
      command: nvim --headless "+Lazy! restore" -c qa
  tags: [nvim]

- name: install and configure starship
  block:
    - name: enable copr repo
      community.general.copr:
        name: atim/starship
        state: enabled
      when: ansible_facts.os_family|lower == "redhat"
      become: true

    - name: install
      import_tasks: "{{ playbook_dir }}/shared/install.yml"
      vars:
        packages:
          - starship

    - name: setup starship config
      import_tasks: "{{ playbook_dir }}/shared/copy.yml"
      vars:
        src: "{{ files_path }}/starship/"
        dest: "{{ config_dir }}/starship"
  tags: [starship]

- import-tasks: homebrew.yml
  tags: [homebrew]
