- name: create required directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ ansible_env.HOME }}/.local/bin"
    - "{{ ansible_env.HOME }}/.local/share"
    - "{{ ansible_env.HOME }}/.local/share/applications"

- import_tasks: fish.yml
  tags: [fish]

- import_tasks: nvim.yml
  tags: [nvim]

- name: install and configure starship
  block:
    - name: enable copr repo
      community.general.copr:
        name: atim/starship
        state: enabled
      when: ansible_facts.os_family|lower == "redhat"
      become: true

    - name: install
      import_tasks: "{{ playbook_dir }}/shared/install.yml"
      vars:
        packages:
          - starship

    - name: setup starship config
      import_tasks: "{{ playbook_dir }}/shared/copy.yml"
      vars:
        src: "{{ files_path }}/starship/"
        dest: "{{ config_dir }}/starship"
  tags: [starship]

- import_tasks: homebrew.yml
  tags: [homebrew]
