- import_tasks: fish.yml
  tags: [ fish ]

- name: install and configure nvim
  block:
    - name: install
      import_tasks: "{{ playbook_dir }}/shared/install.yml"
      vars:
        packages:
          - neovim

    - name: create neovim config directory
      ansible.builtin.file:
        state: directory
        path: "{{ nvim_conf_dir }}"

    - name: setup neovim config files
      import_tasks: "{{ playbook_dir }}/shared/copy.yml"
      vars:
        src: "{{ files_path }}/nvim/{{ item }}"
        dest: "{{ nvim_conf_dir }}/{{ item | trim('/')}}"
        loop:
          - after/
          - ftplugin/
          - init.lua
          - lazy-lock.json
          - lua/

    - name: setup plugins
      command: nvim --headless "+Lazy! restore" +qa
  tags: [ nvim ]

- name: install and setup fnm
  block:
    - name: download fnm archive
      ansible.builtin.get_url:
        url: https://github.com/Schniz/fnm/releases/latest/download/fnm-{{ fnm_arch | trim }}.zip
        dest: "{{ dot_cache_dir }}/fnm.zip"
        mode: '0644'
      when: (fnm_arch)
      register: result

    - name: extract fnm
      ansible.builtin.unarchive:
        src: "{{ result.dest }}"
        dest: "{{ ansible_env.HOME }}/.local/bin"
        mode: '0755'
        remote_src: yes
      when: (fnm_arch) and result.changed
  tags: [ fnm ]

- name: install and configure starship
  block:
    - name: enable copr repo
      community.general.copr:
        name: atim/starship
        state: enabled
      when: ansible_facts.os_family|lower == "redhat"
      become: yes

    - name: install
      import_tasks: "{{ playbook_dir }}/shared/install.yml"
      vars:
        packages:
          - starship

    - name: setup starship config
      import_tasks: "{{ playbook_dir }}/shared/copy.yml"
      vars:
        src:  "{{ files_path }}/starship/"
        dest: "{{ config_dir }}/starship"
  tags: [ starship ]
