- import_tasks: fish.yml
  tags: [ fish ]

- name: create required directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ ansible_env.HOME }}/.local/bin"

- name: install and configure nvim
  block:
    - name: install
      import_tasks: "{{ playbook_dir }}/shared/install.yml"
      vars:
        packages:
          - neovim

    - name: create neovim config directory
      ansible.builtin.file:
        state: directory
        path: "{{ nvim_conf_dir }}"

    - name: setup neovim config files
      import_tasks: "{{ playbook_dir }}/shared/copy.yml"
      vars:
        src: "{{ files_path }}/nvim/{{ item }}"
        dest: "{{ nvim_conf_dir }}/{{ item | trim('/')}}"
        items:
          - after/
          - ftplugin/
          - init.lua
          - lazy-lock.json
          - lua/

    - name: setup plugins
      command: nvim --headless "+Lazy! restore" +qa
  tags: [ nvim ]

- name: install and configure starship
  block:
    - name: enable copr repo
      community.general.copr:
        name: atim/starship
        state: enabled
      when: ansible_facts.os_family|lower == "redhat"
      become: yes

    - name: install
      import_tasks: "{{ playbook_dir }}/shared/install.yml"
      vars:
        packages:
          - starship

    - name: setup starship config
      import_tasks: "{{ playbook_dir }}/shared/copy.yml"
      vars:
        src:  "{{ files_path }}/starship/"
        dest: "{{ config_dir }}/starship"
  tags: [ starship ]

- name: setup homebrew
  block:
    - name: test if homebrew is installed
      ansible.builtin.stat:
        path: "{{ homebrew_prefix }}/bin/brew"
      register: brew_stat

    - name: install homebrew
      block:
        - name: create homebrew prefix
          ansible.builtin.file:
            state: directory
            owner: "{{ ansible_env.USER }}"
            group: "{{ ansible_env.USER }}"
            mode: '0755'
            path: "{{ homebrew_prefix }}"
          become: yes

        - name: create homebrew directories
          ansible.builtin.file:
            state: directory
            path: "{{ homebrew_prefix }}/{{ item }}"
          loop: "{{ homebrew_mkdirs }}"

        - name: setup homebrew repo
          block:
            - name: create homebrew repo
              ansible.builtin.file:
                state: directory
                path: "{{ homebrew_repo }}"

            - name: initialize homebrew repo
              ansible.builtin.command:
                cmd: git -c init.defaultBranch=main init --quiet
                chdir: "{{ homebrew_repo }}"
                creates: "{{ homebrew_repo }}/.git"

            - name: setup homebrew repo config
              community.general.git_config:
                scope: local
                repo: "{{ homebrew_repo }}"
                name: "{{ item.key }}"
                value: "{{ item.value }}"
              loop: "{{ config | dict2items }}"
              vars:
                config:
                  remote.origin.url: https://github.com/Homebrew/brew
                  remote.origin.fetch: "+refs/heads/*:refs/remotes/origin/*"
                  fetch.prune: "true"
                  core.autocrlf: "false"
                  core.symlinks: "true"

            - name: fetch homebrew upstream
              ansible.builtin.command:
                cmd: git fetch --quiet --force origin
                chdir: "{{ homebrew_repo }}"

            - name: fetch homebrew upstream tags
              ansible.builtin.command:
                cmd: git fetch --quiet --force --tags origin
                chdir: "{{ homebrew_repo }}"

            - name: get homebrew tags
              ansible.builtin.command:
                cmd: git -c "column.ui=never" tag --list --sort="-version:refname"
                chdir: "{{ homebrew_repo }}"
              register: brew_tags

            - name: checkout latest homebrew tag
              ansible.builtin.command:
                cmd: git checkout --quiet --force -B stable "{{ brew_tags.stdout_lines[0] }}"
                chdir: "{{ homebrew_repo }}"

            - name: link homebrew executable
              ansible.builtin.file:
                state: link
                src: "{{ homebrew_repo }}/bin/brew"
                dest: "{{ homebrew_prefix }}/bin/brew"
          vars:
            homebrew_repo: "{{ homebrew_prefix }}/Homebrew"
      when: not brew_stat.stat.exists

    - name: update homebrew
      ansible.builtin.command:
        argv: 
          - "{{ homebrew_prefix }}/bin/brew"
          - update
          - --force
          - --quiet

    - name: install homebrew applications
      community.general.homebrew:
        name: [ eza, fnm ]
        state: present
  tags: [ homebrew ]
