- name: lazyvim install check
  ansible.builtin.stat:
    path: "{{ nvim_conf_dir }}/lazyvim.json"
  register: lazyvim
  tags: [nvim]

- name: prep for nvim install
  block:
    - name: backup old neovim config directory
      ansible.builtin.command:
        cmd: "mv {{ nvim_conf_dir }} {{ nvim_conf_dir }}.bak/"
        creates: "{{ nvim_conf_dir }}.bak"
        removes: "{{ nvim_conf_dir }}"

    - name: remove old state files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ ansible_env.HOME }}/.local/share/nvim"
        - "{{ ansible_env.HOME }}/.local/state/nvim"
        - "{{ cache_dir }}/nvim"
  when: not lazyvim.stat.exists
  tags: [nvim]

- name: install and configure nvim
  block:
    - name: install
      import_tasks: "{{ playbook_dir }}/shared/install.yml"
      vars:
        packages:
          - neovim

    - name: create base nvim config
      ansible.builtin.file:
        path: "{{ nvim_conf_dir }}"
        state: directory

    - name: create nvim config subdirs
      ansible.builtin.file:
        path: "{{ nvim_conf_dir }}/{{ item.path }}"
        state: directory
      loop: "{{ nvim_conf_items }}"
      when: item.state == 'directory'
      loop_control:
        label: "{{ item.path }}"

    - name: link nvim config files
      import_tasks: "{{ playbook_dir }}/shared/copy.yml"
      vars:
        src: "{{ item.src }}"
        dest: "{{ nvim_conf_dir }}/{{ item.path }}"
        items: "{{ nvim_conf_items | selectattr('state', 'eq', 'file') }}"

  tags: [nvim]
