- name: create profile directory
  become: yes
  ansible.builtin.file:
    state: directory
    path: "/etc/profile.d"
  register: profiled

- name: setup profile files
  import_tasks: "{{ playbook_dir }}/shared/copy.yml"
  vars:
    dest: "{{ profiled.path }}/environment.sh"
    src: "{{ files_path }}/environment.sh"
  become: yes
