- name: install base utilities
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    title: "utilities"
    packages:
      - bat
      - eza
      - fd-find
      - fzf
      - git
      - lua
      - ripgrep
      - trash-cli
  tags: [ utilities ]

- name: setup shell environment
  import_tasks: environment.yml
  tags: [ environment ]

- name: start ssh agent
  ansible.builtin.systemd:
    scope: user
    unit: ssh-agent.service
    enabled: true
