# input configuration
# vim: ft=swayconfig

# force numlock on at start
input type:keyboard xkb_numlock enabled

# enable compose key
input 7504:24926:Corne-ish_Zen_Keyboard xkb_options "compose:ralt"

### Glourius O2
input 2362:33325:Glorious_Model_O_2_Wireless_Mouse {
    # wireless
    accel_profile flat
    pointer_accel -0.45
}
input 2362:33322:GLORIOUS_Model_O_2_Wireless_Mouse {
    # wired
    accel_profile flat
    pointer_accel -0.45
}

### Pulsar X3 Mini Crazylight
input 14096:21510:Pulsar_8K_Dongle_Gen.2 {
    # wireless
    accel_profile flat
    pointer_accel -0.4
}
input 14096:13575:Pulsar_X3_CrazyLight {
    # wired
    accel_profile flat
    pointer_accel -0.4
}

# mousekeys
input 7504:24926:ZMK_Project_Corne-ish_Zen_Mouse {
    accel_profile adaptive
    pointer_accel 1
}
