# workspaces
# vim: ft=swayconfig

# workspace arrangement
workspace $ws1 output $mon1
workspace $ws4 output $mon1
workspace $ws7 output $mon1

workspace $ws2 output $mon2
workspace $ws5 output $mon2
workspace $ws8 output $mon2

workspace $ws3 output $mon3
workspace $ws6 output $mon3
workspace $ws9 output $mon3

workspace number $ws1
focus_on_window_activation urgent

# Discord
assign [app_id="^discord$"] workspace $ws3
no_focus [app_id="^discord$"]
for_window [app_id="^discord$"] border csd

assign [app_id="^vesktop$"] workspace $ws3
no_focus [app_id="^vesktop$"]
for_window [app_id="^vesktop$"] border csd

# Signal
assign [class="^Signal$"] workspace $ws3
assign [app_id="^org\.signal\.Signal$"] workspace $ws3

# Steam
for_window [class="^steam$" title="^Steam Settings$"] floating enable
for_window [class="^steam$" title="^Friends List$"] floating enable
assign [class="^steam$"] workspace $ws6
no_focus [class="^steam$"]

# Gamed
#for_window [class="cs2"] fullscreen enable
#assign [class="cs2"] workspace $ws5

for_window [class="^RimWorldLinux$"] fullscreen enable

# Lutris
assign [class="^Lutris$"] workspace $ws6

# Origin (Lutris)
for_window [instance="^origin.exe$" class="Wine"] floating enable, fullscreen disable

# Heroic
assign [class="^heroic"] workspace $ws6

# Mail
assign [app_id="^Proton Mail$"] workspace $ws1
no_focus [app_id="^Proton Mail$"]
assign [class="^Proton Mail$"] workspace $ws1
no_focus [class="^Proton Mail$"]

assign [app_id="^net.thunderbird.Thunderbird$"] workspace $ws1
no_focus [app_id="^net.thunderbird.Thunderbird$"]

# Nextcloud
for_window [app_id="^com.nextcloud.desktopclient.nextcloud$"] floating enable, resize set 450 600, focus, move position cursor
