- name: create directory
  become: yes
  ansible.builtin.file:
    state: directory
    path: "/etc/profile.d"
  register: profiled

- name: link profile files
  become: yes
  ansible.builtin.file:
    state: link
    name: "{{ profiled.path }}/{{ item }}"
    src: "{{ files_path }}/{{ item }}"
  loop:
    - environment.sh

- name: create bashrc
  ansible.builtin.file:
    state: file
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: setup bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      exec fish
