- name: Setup local environment
  hosts: localhost
  roles:
    - config
    - role: i3
      tags: [ gui, wm ]
    - role: py3status
      tags: [ gui, wm ]
    - role: rofi
      tags: [ gui, util ]
    - role: kitty
      tags: [ gui, util, term ]
    - role: neovim
      tags: [ cli, util ]
    - role: vim
      tags: [ vim, never ]
    - role: zsh
      tags: [ cli, term, util ]
    - role: gui-scripts
      tags: [ gui, util ]
