- name: Setup local environment
  hosts: localhost
  roles:
    - role: profile
      tags: [ cli, term, env ]
    - role: fish
      tags: [ cli, term, fish ]
    - role: neovim
      tags: [ cli, neovim ]
    - role: i3
      tags: [ gui, wm, i3 ]
    - role: py3status
      tags: [ gui, wm, py3status ]
    - role: rofi
      tags: [ gui, wm, rofi ]
    - role: kitty
      tags: [ gui, term, kitty ]
    - role: gui-scripts
      tags: [ gui, scripts ]
    - role: utils
      tags: [ utils ]
    - role: zsh
      tags: [ zsh, never ]
    - role: nvm
      tags: [ nvm, never ]
    - role: vim
      tags: [ vim, never ]
