- name: Setup local environment
  hosts: localhost
  roles:
    - role: i3
      tags: [ gui, wm, i3 ]
    - role: py3status
      tags: [ gui, wm, py3status ]
    - role: rofi
      tags: [ gui, util, rofi ]
    - role: kitty
      tags: [ gui, util, term, kitty ]
    - role: neovim
      tags: [ cli, util, neovim ]
    - role: vim
      tags: [ vim, never ]
    - role: zsh
      tags: [ cli, term, util, zsh ]
    - role: gui-scripts
      tags: [ gui, util, scripts ]
