- name: Setup local environment
  hosts: localhost
  pre_tasks:
    - name: OS check
      ansible.builtin.fail: msg="OS '{{ ansible_facts.os_family }}' is not supported"
      when: ansible_facts.os_family|lower != "redhat"
      tags: [ always ]
  roles:
    - role: 00-base
      tags: [ base ]
    - role: 01-cli
      tags: [ cli ]
    - role: 02-gui
      tags: [ gui ]
