#!/usr/bin/env bash
set -euo pipefail

tags="${1-all}"

# exit if ansible not available
if ! [ -x "$(command -v ansible)" ]; then
    echo "ansible must be installed"
    exit 2
fi

# ensure expected environment
source roles/config/files/zsh/zshenv

# run playbook
ansible-playbook -i ./hosts ./dotfiles.yml --tags ${tags}

# alert on finish
tput bel
