#!/usr/bin/env bash
set -euo pipefail

tags="${1-all}"

# exit if ansible not available
if ! [ -x "$(command -v ansible)" ]; then
    echo "ansible must be installed"
    exit 2
fi

# ensure expected environment
source roles/00-base/files/environment.sh

# run playbook
ansible-playbook -K -i ./hosts ./dotfiles.yml --tags "${tags}"

# alert on finish
tput bel
