- name: setup scripts
  import_tasks: "{{ playbook_dir }}/shared/copy.yml"
  vars:
    src: "{{ files_path }}/scripts/{{ item }}"
    dest: "{{ local_bin_dir }}/{{ item }}"
    items: "{{ scripts }}"
