- name: create sway config directory
  ansible.builtin.file:
    state: directory
    name: "{{ config_dir }}/sway"
  register: sway_config

- name: setup sway config
  import_tasks: "{{ playbook_dir }}/shared/copy.yml"
  vars:
    src: "{{ files_path }}/sway/{{ item }}"
    dest: "{{ sway_config.path }}/{{ item | trim('/')}}"
    items:
      - config
      - "{{ ansible_hostname }}/"

- name: install base groups
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    packages:
      - "@swaywm"
      - "@swaywm-extended"

- name: create autostart directory
  ansible.builtin.file:
    state: directory
    name: "{{ config_dir }}/autostart"
  register: autostart

- name: set polkit to autostart
  ansible.builtin.copy:
    src: "/etc/xdg/autostart/lxqt-policykit-agent.desktop"
    dest: "{{ autostart.path }}/lxqt-policykit-agent.desktop"

- name: allow polkit to start on sway
  ansible.builtin.replace:
    path: "{{ autostart.path }}/lxqt-policykit-agent.desktop"
    regexp: '^OnlyShowIn=\S+$'
