- name: create sway config directory
  ansible.builtin.file:
    state: directory
    name: "{{ config_dir }}/sway"
  register: sway_config

- name: setup sway config
  import_tasks: "{{ playbook_dir }}/shared/copy.yml"
  vars:
    src: "{{ files_path }}/sway/{{ item }}"
    dest: "{{ sway_config.path }}/{{ item | trim('/')}}"
    loop:
      - config
      - "{{ ansible_hostname }}/"

- name: install base group
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    packages:
      - "@swaywm"
