- name: create zsh directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ config_dir }}/zsh"
    - "{{ cache_dir }}/zsh"
  register: zsh_dirs

- name: link zsh config
  ansible.builtin.file:
    state: link
    name: "{{ zsh_dirs.results[0].path }}/{{ item }}"
    src: "{{ files_path }}/{{ item }}"
  loop:
    - .zshrc
    - .zshenv
    - alias.zsh
    - functions.zsh
    - keybind.zsh
    - p10k.tty.zsh
    - p10k.zsh

- name: link zshenv
  ansible.builtin.file:
    state: link
    name: "{{ ansible_env.HOME }}/.zshenv"
    src: "{{ files_path }}/.zshenv"
