- name: create zsh directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ config_dir }}/zsh"
    - "{{ cache_dir }}/zsh"
  register: zsh_dirs

- name: link main config
  ansible.builtin.file:
    state: link
    name: "{{ ansible_env.HOME }}/.{{ item }}"
    src: "{{ files_path }}/{{ item }}"
  loop:
    - zshrc
    - zshenv

- name: link zsh config
  ansible.builtin.file:
    state: link
    name: "{{ zsh_dirs.results[0].path }}/{{ item }}"
    src: "{{ files_path }}/{{ item }}"
  loop:
    - alias.zsh
    - functions.zsh
    - keybind.zsh
    - p10k
