# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$all\
$cmd_duration\
$character
"""
#right_format = '$cmd_duration$time'

[directory]
format = '[$read_only]($read_only_style)[$path]($style) '
fish_style_pwd_dir_length = 1

[character]
vimcmd_symbol = '[❮](bold red)'

[cmd_duration]
format = '[$duration]($style) '

[package]
disabled = true

[time]
disabled = true

[fill]
symbol = ' '

[git_status]
format = '([\[$all_status$ahead_behind\]](bold purple) )'
ahead = '[⇡$count](blue)'
behind = '[⇣$count](red)'
diverged = '[⇕$ahead_count/$behind_count](purple)'
untracked = '[?$count](bold bright-yellow)'
stashed = '[\$$count](cyan)'
modified = '[!$count](bold bright-red)'
staged = '[+$count](bright-green)'
renamed = '[»$count](green)'
deleted = '[✘$count](bright-black)'

[golang]
symbol = ' '
