- name: create kitty config dir
  ansible.builtin.file:
    state: directory
    path: "{{ config_dir }}/kitty"
  register: kitty_conf

- name: link kitty config
  ansible.builtin.file:
    state: link
    name: "{{ kitty_conf.path }}/kitty.conf"
    src: "{{ files_path }}/kitty.conf"

- name: check if theme is set
  ansible.builtin.stat:
    path: "{{ kitty_conf.path }}/current-theme.conf"
  register: theme_file

- name: copy kitty theme
  ansible.builtin.copy:
    src: current-theme.conf
    dest: "{{ kitty_conf.path }}/current-theme.conf"
  when: theme_file.stat.exists == false
