- name: create kitty config dir
  ansible.builtin.file:
    state: directory
    path: "{{ config_dir }}/kitty"
  register: kitty_conf

- name: link kitty config
  ansible.builtin.file:
    state: link
    name: "{{ kitty_conf.path }}/kitty.conf"
    src: "{{ files_path }}/kitty.conf"

- name: install
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    packages:
      - kitty
