- import_tasks: config.yml
  tags: [ config ]

- name: Install i3 on Arch
  import_tasks: arch.yml
  when: ansible_facts.os_family|lower == "archlinux"
  tags: [ install, pacman ]

- name: Install i3 on Fedora/RHEL
  import_tasks: rhel.yml
  when: ansible_facts.os_family|lower == "redhat"
  tags: [ install, dnf ]
