#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2.0

[[blocks]]
  alignment = "left"
  type = "prompt"
  newline = true

  [[blocks.segments]]
    background = "transparent"
    foreground = "blue"
    style = "plain"
    template = " {{ .Path }}"
    type = "path"
    [blocks.segments.properties]
      style = "powerlevel"

[[blocks]]
  alignment = "right"
  type = "prompt"

  [[blocks.segments]]
    background = "transparent"
    foreground = "#43CCEA"
    foreground_templates = ["{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}", "{{ if gt .Ahead 0 }}#B388FF{{ end }}", "{{ if gt .Behind 0 }}#B388FF{{ end }}"]
    leading_diamond = " \ue0b6"
    style = "plain"
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} "
    trailing_diamond = "\ue0b4"
    type = "git"
    [blocks.segments.properties]
      branch_max_length = 25.0
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    background = "transparent"
    foreground = "#E4F34A"
    leading_diamond = " \ue0b6"
    style = "plain"
    template = "\ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4"
    type = "python"
    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "transparent"
    foreground = "#7FD5EA"
    leading_diamond = " \ue0b6"
    style = "plain"
    template = "\ufcd1{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4"
    type = "go"
    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "transparent"
    foreground = "#42E66C"
    leading_diamond = " \ue0b6"
    style = "plain"
    template = "\ue718{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"
    trailing_diamond = "\ue0b4"
    type = "node"
    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "transparent"
    foreground = "#E64747"
    leading_diamond = " \ue0b6"
    style = "plain"
    template = "\ue791{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4"
    type = "ruby"
    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "transparent"
    foreground = "#E64747"
    leading_diamond = " \ue0b6"
    style = "plain"
    template = "\ue738{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = "\ue0b4"
    type = "java"
    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "transparent"
    foreground = "#9B6BDF"
    leading_diamond = " \ue0b6"
    style = "plain"
    template = "\ue624{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    trailing_diamond = "\ue0b4"
    type = "julia"
    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "transparent"
    foreground = "#ffffff"
    leading_diamond = " \ue0b6"
    style = "plain"
    template = "\ue73d {{ .Full }} "
    trailing_diamond = "\ue0b4"
    type = "php"
    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "transparent"
    foreground = "#9B6BDF"
    foreground_templates = ["{{if eq \"Charging\" .State.String}}#40c4ff{{end}}", "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}", "{{if eq \"Full\" .State.String}}#4caf50{{end}}"]
    leading_diamond = " \ue0b6"
    style = "plain"
    template = "{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}"
    trailing_diamond = "\ue0b4"
    type = "battery"
    [blocks.segments.properties]
      charged_icon = " "
      charging_icon = "\u21e1 "
      discharging_icon = "\u21e3 "

[[blocks]]
  alignment = "left"
  newline = true
  type = "prompt"

  [[blocks.segments]]
    background = "transparent"
    foreground = "#AEA4BF"
    leading_diamond = "\ue0b6"
    style = "plain"
    template = "{{ .FormattedMs }} "
    trailing_diamond = "\ue0b4 "
    type = "executiontime"
    [blocks.segments.properties]
      style = "austin"
      threshold = 150.0

  [[blocks.segments]]
    background = "transparent"
    foreground = "blue"
    style = "plain"
    template = "{{ if .SSHSession }}{{ .UserName }}@{{ .HostName }}{{end}}"
    type = "session"

  [[blocks.segments]]
    background = "transparent"
    foreground = "#E64747"
    foreground_templates = [
      "{{ if eq .Code 0 }}green{{ end }}"
    ]
    style = "plain"
    template = "❯"
    type = "text"

[transient_prompt]
  background = "transparent"
  foreground = "green"
  template = "❯ "
