- name: install gui utilities
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    title: gui
    packages: "{{ gui.packages }}"
    arch_packages: "{{ gui.arch_packages }}"
    rhel_packages: "{{ gui.rhel_packages }}"
  tags: [ gui ]

- name: install cli utilities
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    title: "cli"
    packages: "{{ cli.packages }}"
    arch_packages: "{{ cli.arch_packages }}"
    rhel_packages: "{{ cli.rhel_packages }}"
  tags: [ cli ]
