- name: download fnm archive
  ansible.builtin.get_url:
    url: https://github.com/Schniz/fnm/releases/latest/download/fnm-{{ arch | trim }}.zip
    dest: "/tmp/fnm.zip"
    mode: '0644'
  when: (arch)
  register: result

- name: extract fnm
  ansible.builtin.unarchive:
    src: "{{ result.dest }}"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: '0755'

- name: remove fnm archive
  ansible.builtin.file:
    state: absent
    path: "{{ result.dest }}"
