font_family         Hack Nerd Font Mono
font_size           12
enable_audio_bell   no

tab_bar_edge        top
tab_bar_style       slant

background_opacity 0.98

# set shell to use (since login shell is bash for compatability)
shell fish
shell_integration   enabled

# additional scrollback size in MB (approx 10_000 lines per MB)
scrollback_pager_history_size 2

# layout
enabled_layouts splits:split_axis=horizontal,stack

allow_remote_control yes
listen_on unix:@mykitty

# set mod
kitty_mod ctrl+shift
clear_all_shortcuts no

# window creation
map kitty_mod+n>F5 launch --location=vsplit
map kitty_mod+n>F6 launch --location=hsplit
map kitty_mod+n>n new_os_window

map kitty_mod+alt+n>F5 launch --location=vsplit --cwd=current
map kitty_mod+alt+n>F6 launch --location=hsplit --cwd=current
map kitty_mod+alt+n>n new_os_window_with_cwd

map kitty_mod+enter launch --location=split
map kitty_mod+alt+enter launch --location=split --cwd=current

map kitty_mod+t new_tab
map kitty_mod+alt+t new_tab_with_cwd

# layout manipulation
map kitty_mod+F7 layout_action rotate
map kitty_mod+space next_layout

# Switch focus to the neighboring window in the indicated direction
map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l

# Move the active window in the indicated direction
map shift+left move_window left
map shift+down move_window down
map shift+up move_window up
map shift+right move_window right

# Move the active window to the indicated screen edge
map kitty_mod+up layout_action move_to_screen_edge top
map kitty_mod+left layout_action move_to_screen_edge left
map kitty_mod+right layout_action move_to_screen_edge right
map kitty_mod+down layout_action move_to_screen_edge bottom

# Set the bias of the split containing the currently focused window. The
# currently focused window will take up the specified percent of its parent
# window's size.
map ctrl+. layout_action bias 80
map ctrl+, layout_action bias 50

# additional shortcuts
map ctrl+alt+enter no_op

include theme.conf
