- name: install kitty
  ansible.builtin.package:
    name: kitty
    state: present
  become: yes

- name: create kitty config dir
  ansible.builtin.file:
    path: ~/.config/kitty/
    state: directory

- name: copy kitty config
  ansible.builtin.copy:
    src: kitty.conf
    dest: ~/.config/kitty/kitty.conf

- name: copy kitty theme
  ansible.builtin.copy:
    src: current-theme.conf
    dest: ~/.config/kitty/current-theme.conf
