- name: create neovim config directory
  ansible.builtin.file:
    state: directory
    path: "{{ config_dir }}/nvim"

- name: link neovim config files
  ansible.builtin.file:
    state: link
    name: "{{ config_dir }}/nvim/{{ item }}"
    src: "{{ files_path }}/nvim/{{ item }}"
  loop:
    - init.lua
    - lua
