- name: create zsh config directory
  ansible.builtin.file:
    state: directory
    path: "{{ config_dir }}/zsh"

- name: link zsh config
  ansible.builtin.file:
    state: link
    name: "{{ config_dir }}/zsh/{{ item }}"
    src: "{{ files_path }}/zsh/{{ item }}"
  loop:
    - .zshrc
    - alias.zsh
    - functions.zsh
    - keybind.zsh
    - p10k.tty.zsh
    - p10k.zsh

- name: link zshenv
  ansible.builtin.file:
    state: link
    name: "{{ ansible_env.HOME }}/.zshenv"
    src: "{{ files_path }}/zsh/zshenv"
