- name: create zsh config directory
  ansible.builtin.file:
    path: "{{ config_dir }}/zsh"
    state: directory

- name: copy zsh config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ config_dir }}/zsh/{{ item | basename }}"
  loop:
    - zsh/config.zsh
    - zsh/keybind.zsh
    - zsh/p10k.tty.zsh
    - zsh/p10k.zsh

- name: copy zshrc
  ansible.builtin.copy:
    src: zsh/zshrc.dist
    dest: ~/.zshrc
