- name: create zsh config directory
  ansible.builtin.file:
    state: directory
    path: "{{ config_dir }}/zsh"

- name: link zsh config
  ansible.builtin.file:
    state: link
    name: "{{ config_dir }}/zsh/{{ item }}"
    src: "{{ files_path }}/zsh/{{ item }}"
  loop:
    - config.zsh
    - keybind.zsh
    - p10k.tty.zsh
    - p10k.zsh

- name: link zshrc
  ansible.builtin.file:
    state: link
    name: "{{ ansible_env.HOME }}/.zshrc"
    src: "{{ files_path }}/zsh/zshrc.dist"
