- name: create neovim config directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory

- name: symlink neovim config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.config/nvim/{{ item }}"
  loop:
    - init.lua
    - lua/
