- name: create rofi config directory
  ansible.builtin.file:
    state: directory
    name: "{{ config_dir }}/rofi"
  register: rofi_config

- name: link rofi config
  ansible.builtin.file:
    state: link
    name: "{{ rofi_config.path }}/{{ item }}"
    src: "{{ files_path }}/{{ item }}"
  loop:
    - launcher.rasi
