fnm_arch: >-
  {% if ansible_architecture == 'x86_64' %}linux
  {% elif ansible_architecture == 'armv7l' %}arm32
  {% else %}{% endif %}

fish_conf_dir: "{{ config_dir }}/fish"
nvim_conf_dir: "{{ config_dir }}/nvim"

homebrew_prefix: /home/linuxbrew/.linuxbrew/
homebrew_mkdirs:
  - bin
  - etc
  - include
  - lib
  - sbin
  - share
  - var
  - opt
  - share/zsh
  - share/zsh/site-functions
  - var/homebrew
  - var/homebrew/linked
  - Cellar
  - Caskroom
  - Frameworks
