- name: create local bin
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.HOME }}/.local/bin"
  register: bin_dir

- name: link scripts
  ansible.builtin.file:
    state: link
    name: "{{ bin_dir.path }}/{{ item }}"
    src: "{{ files_path }}/{{ item }}"
  loop:
    - scrot
    - i3locker
    - i3exit
    - launcher
