de_scripts:
  - launcher
  - scrot-wl
  - swayidle-hibernate
  - swaylocker
  - switcher
  - wmexit

de_utils:
  - ImageMagick
  - gammastep
  - playerctl
  - waybar

setup_de: "{{ ansible_env.DOT_DESKTOP is defined and ansible_env.DOT_DESKTOP | bool }}"

fonts:
  - { name: hack-nerd-font, src: Hack.zip }
  - { name: firacode-nerd-font, src: FiraCode.zip }
  - { name: jetbrainsmono-nerd-font, src: JetBrainsMono.zip }
