de_scripts:
  - launcher
  - scrot-wl
  - swayidle-hibernate
  - swaylocker
  - switcher
  - volume-tracker
  - volume-notifier
  - wmexit

de_utils:
  - ImageMagick
  - gammastep
  - playerctl
  - waybar

setup_de: false

fonts:
  - { name: hack-nerd-font, src: Hack.zip }
  - { name: firacode-nerd-font, src: FiraCode.zip }
  - { name: jetbrainsmono-nerd-font, src: JetBrainsMono.zip }

kitty_dir: "$XDG_DATA_HOME/kitty.app"
