de_scripts:
  - launcher
  - scrot-wl
  - swayidle-hibernate
  - swaylocker
  - switcher
  - wmexit

de_utils:
  - ImageMagick
  - gammastep
  - playerctl
  - waybar

setup_de: "{{ ansible_env.DOT_DESKTOP is defined and ansible_env.DOT_DESKTOP | bool }}"
