xorg_scripts:
  - i3locker
  - scrot

wayland_scripts:
  - scrot-wl
  - swayidle-hibernate
  - swaylocker

shared_scripts:
  - launcher
  - switcher
  - wmexit

xorg_utils:
  - maim
  - py3status
  - redshift
  - xdotool
  - xset

wayland_utils:
  - gammastep
  - waybar

shared_utils:
  - ImageMagick
  - playerctl

use_xorg: "{{ ansible_env.DOT_XORG is defined and ansible_env.DOT_XORG | bool }}"
use_wayland: "{{ ansible_env.DOT_WAYLAND is defined and ansible_env.DOT_WAYLAND | bool }}"
