xorg_scripts:
  - scrot
  - i3exit
  - i3locker

shared_scripts:
  - launcher
  - switcher

xorg_utils:
  - maim
  - xdotool
  - xset

shared_utils:
  - playerctl
  - ImageMagick

use_xorg: "{{ ansible_env.DOT_XORG is defined and ansible_env.DOT_XORG | bool }}"
use_wayland: "{{ ansible_env.DOT_WAYLAND is defined and ansible_env.DOT_WAYLAND | bool }}"
