xorg_scripts:
  - scrot
  - i3locker

wayland_scripts:
  - scrot-wl
  - swaylocker

shared_scripts:
  - launcher
  - switcher
  - wmexit

xorg_utils:
  - maim
  - xdotool
  - xset

wayland_utils: []

shared_utils:
  - playerctl
  - ImageMagick

use_xorg: "{{ ansible_env.DOT_XORG is defined and ansible_env.DOT_XORG | bool }}"
use_wayland: "{{ ansible_env.DOT_WAYLAND is defined and ansible_env.DOT_WAYLAND | bool }}"
