- name: create {{ repo }} dir
  ansible.builtin.file:
    state: directory
    path: "{{ dot_cache_dir }}/git/{{ repo | regex_replace('\/', '__') }}"
  register: repo_dir

- name: clone {{ repo }}
  ansible.builtin.git:
    repo: https://github.com/{{ repo }}.git
    dest: "{{ repo_dir.path }}"
    single_branch: yes
    version: "{{ branch | default('HEAD') }}"

- name: get latest tag for {{ repo }}
  block:
    - name: list tags of {{ repo }}
      ansible.builtin.shell:
        cmd: "git describe --tags"
        chdir: "{{ repo_dir.path }}"
      register: git_tag
      check_mode: false

    - name: checkout latest tag of {{ repo }}
      ansible.builtin.git:
        repo: https://github.com/{{ repo }}.git
        dest: "{{ repo_dir.path }}"
        single_branch: yes
        version: "{{ git_tag.stdout }}"
  when: latest is defined and latest
