- name: "install {{ packages | join(', ') }}"
  become: yes
  ansible.builtin.dnf5:
    auto_install_module_deps: true
    name: "{{ packages | default([]) }}"
    exclude: "{{ exclude | default([]) }}"
    allowerasing: "{{ erase | default(True) }}"
    state: "{{ state | default('latest') }}"
