- name: "install {{ packages | join(', ') }}"
  become: yes
  ansible.builtin.dnf:
    name: "{{ packages | default([]) }}"
    exclude: "{{ exclude | default([]) }}"
    allowerasing: "{{ erase | default(True) }}"
    state: "{{ state | default('latest') }}"
