zmodload zsh/zprof

# source default configurations
source ~/.dotfiles/zsh/config.zsh
source ~/.dotfiles/zsh/keybind.zsh

# add custom commands below here
################################

export EDITOR=nvim
export SUDO_EDITOR=nvim

# Set up Node Version Manager
source /usr/share/nvm/init-nvm.sh --no-use

path+=("${HOME}/go/bin")

# Created by `pipx` on 2021-10-15 21:30:30
path+=("${HOME}/.local/bin")
