## Autostart Tmux on shell launch
# Uncomment to activate. Recommended only for workstations
export ZSH_TMUX_AUTOSTART=true

# source default zshrc
source ~/.dotfiles/zsh/config.zsh
# add custom commands below here
################################

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

# added by pipx (https://github.com/pipxproject/pipx)
export PATH="/home/erik/.local/bin:$PATH"

# symfony
export PATH="$HOME/.symfony/bin:$PATH"

#android sdk
export PATH="$PATH:$HOME/android/tools/bin"
