- name: enable copr repo
  community.general.copr:
    name: atim/starship
    state: enabled
  when: ansible_facts.os_family|lower == "redhat"
  become: yes

- name: install
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    packages:
      - starship

- name: link config
  ansible.builtin.file:
    state: link
    src:  "{{ files_path }}/starship.toml"
    dest: "{{ config_dir }}/starship.toml"
