- name: create neovim config directory
  ansible.builtin.file:
    state: directory
    path: "{{ config_dir }}/nvim"
  register: neovim_conf

- name: link neovim config files
  ansible.builtin.file:
    state: link
    name: "{{ neovim_conf.path }}/{{ item }}"
    src: "{{ files_path }}/{{ item }}"
  loop:
    - init.lua
    - lua
    - after
    - ftplugin

- name: install
  import_tasks: "{{ playbook_dir }}/shared/install.yml"
  vars:
    packages:
      - neovim

- name: setup plugins
  command: nvim --headless -u NONE -c 'lua require("bootstrap").bootstrap()'
